#ifndef CONFIG_MANAGER_h
#define CONFIG_MANAGER_h

// to be substituted if necessary to false
#define USE_CONFIG_MANAGER_EXAMPLES false

#include <WString.h>

class CONFIG_MANAGER{

public:

  // -------------------------------------------------------------------------
  // GENERIC FUNCTIONS -------------------------------------------------------
  // -------------------------------------------------------------------------
  // Those are generic, i.e. not generated by the template and always available
  // -------------------------------------------------------------------------

  // constructor
  CONFIG_MANAGER(void);

  // reset the input parsing state
  void reset_input_parsing(void);

  // read next char; for building the configuration state from  char representation
  int read_next_building_char(char);

  // update field from a (settingName, settingValue) argument
  int update_field(String, String);

  // get ready to start outputting the configuration char representation
  void get_ready_output_char_representation(void);

  // if there are still remaining chars to be flush in the output
  bool remaining_output_char(void);

  // out next char; for building the string representation from the configuration state
  char next_output_char(void);


  // -------------------------------------------------------------------------
  // CUSTOM GENERATED FUNCTIONS ----------------------------------------------
  // -------------------------------------------------------------------------
  // Those are custom generated by the template
  // -------------------------------------------------------------------------

String get_test_var1(void);
void set_test_var1(String);
String getS_test_var1(void);
void setS_test_var1(String);

String get_test_var3(void);
void set_test_var3(String);
String getS_test_var3(void);
void setS_test_var3(String);

int get_test_var2(void);
void set_test_var2(int);
String getS_test_var2(void);
void setS_test_var2(String);

String get_test_var5(void);
void set_test_var5(String);
String getS_test_var5(void);
void setS_test_var5(String);

String get_test_var4(void);
void set_test_var4(String);
String getS_test_var4(void);
void setS_test_var4(String);

String get_test_var7(void);
void set_test_var7(String);
String getS_test_var7(void);
void setS_test_var7(String);

String get_test_var6(void);
void set_test_var6(String);
String getS_test_var6(void);
void setS_test_var6(String);



  #if USE_CONFIG_MANAGER_EXAMPLES

    // NOTE: it may add some overhead and weigth to the sketch to use methods
    // instead of putting all variables as public; make a variant of the code
    // that lets all internals be public?

    // just an example: for the variable defined as ("nbr_index", "int", 0)
    // two functions to get and set from native type
    int get_nbr_index(void);
    void set_nbr_index(int);
    // two functions to get and set from String
    String getS_nbr_index(void);
    void setS_nbr_index(String);

  #endif

private:

  // get one more output line ready for the parser
  void get_output_line_ready(void);

  // -------------------------------------------------------------------------
  // GENERIC VARIABLES -------------------------------------------------------
  // -------------------------------------------------------------------------
  // Those are generic, i.e. not generated by the template and always available
  // -------------------------------------------------------------------------

  // for the parser in
  String settingName;
  String settingValue;
  int state_parser;

  // for the output
  int number_remaining_parameters;
  int crrt_length_output_string;
  int crrt_index_output_string;
  String output_string;
  bool flag_ready_output = false;

  // -------------------------------------------------------------------------
  // CUSTOM GENERATED VARIABLES ----------------------------------------------
  // -------------------------------------------------------------------------
  // Those are custom generated by the template
  // -------------------------------------------------------------------------

String test_var1 = "xx";
String test_var3 = "x2";
int test_var2 = 3;
String test_var5 = "x4";
String test_var4 = "x3";
String test_var7 = "x6";
String test_var6 = "x5";


  #if USE_CONFIG_MANAGER_EXAMPLES

    // just an example: for the variable defined as ("nbr_index", "int", 0)
    int nbr_index = 0;

  #endif

};

#endif
